CREATE TABLE IF NOT EXISTS authtokens (
    id text NOT NULL,
    appid bigint NOT NULL,
    userid bigint NOT NULL,
    entityid bigint NOT NULL,
    entitytype integer NOT NULL,
    scope text NOT NULL,
    time timestamp with time zone NOT NULL,
    CONSTRAINT pk_authtokens PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS buildingrequests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    requesterid bigint NOT NULL,
    provinceid bigint NOT NULL,
    buildingid bigint NULL,
    buildingobjid text NOT NULL,
    levelsrequested integer NOT NULL,
    levelsbuilt integer NOT NULL,
    applied timestamp with time zone NOT NULL,
    actiontime timestamp with time zone NULL,
    reviewed boolean NOT NULL,
    granted boolean NOT NULL,
    reviewerid bigint NULL,
    buildingname text NULL,
    CONSTRAINT pk_buildingrequests PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS cities (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    districtid bigint NOT NULL,
    provinceid bigint NOT NULL,
    iscapitalcity boolean NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS corporations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    groupid bigint NOT NULL,
    CONSTRAINT pk_corporations PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS corporationshareclasses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    corporationid bigint NOT NULL,
    classname integer NOT NULL,
    classtype integer NOT NULL,
    votingpower numeric(9,3) NOT NULL,
    dividendrate numeric(9,3) NOT NULL,
    CONSTRAINT pk_corporationshareclasses PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS corporationshares (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    entityid bigint NOT NULL,
    corporationid bigint NOT NULL,
    shareclassid bigint NOT NULL,
    amount bigint NOT NULL,
    CONSTRAINT pk_corporationshares PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS currenttimes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    time timestamp with time zone NOT NULL,
    CONSTRAINT pk_currenttimes PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS dataprotectionkeys (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    friendlyname text NULL,
    xml text NULL,
    CONSTRAINT pk_dataprotectionkeys PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS elections (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    districtid bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    winnerid bigint NOT NULL,
    choiceids bigint[] NOT NULL,
    type integer NOT NULL,
    CONSTRAINT pk_elections PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS entitybalancerecords (
    entityid bigint NOT NULL,
    time timestamp with time zone NOT NULL,
    incometoday numeric(30,2) NOT NULL,
    balance numeric(30,2) NOT NULL,
    taxablebalance numeric(30,2) NOT NULL,
    CONSTRAINT pk_entitybalancerecords PRIMARY KEY (entityid, time)
);


CREATE TABLE IF NOT EXISTS grouproles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    permissionvalue bigint NOT NULL,
    membersids bigint[] NOT NULL,
    color text NOT NULL,
    groupid bigint NOT NULL,
    salary numeric NOT NULL,
    authority integer NOT NULL,
    CONSTRAINT pk_grouproles PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    grouptype integer NOT NULL,
    flags integer[] NOT NULL,
    open boolean NOT NULL,
    invited bigint[] NOT NULL,
    membersids bigint[] NOT NULL,
    ownerid bigint NOT NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(2048) NULL,
    taxablebalance numeric(30,10) NOT NULL,
    incometoday numeric(30,2) NOT NULL,
    apikey VARCHAR(36) NOT NULL,
    imageurl text NULL,
    nationid bigint NULL,
    money numeric(30,3) NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS itemdefinitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ownerid bigint NOT NULL,
    name text NOT NULL,
    description text NULL,
    created timestamp with time zone NOT NULL,
    baseitemdefinitionid bigint NULL,
    transferable boolean NOT NULL,
    CONSTRAINT pk_itemdefinitions PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS itemtrades (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount double precision NOT NULL,
    definitionid bigint NOT NULL,
    time timestamp with time zone NOT NULL,
    fromid bigint NULL,
    toid bigint NOT NULL,
    details VARCHAR(1024) NOT NULL,
    tradetype integer NOT NULL,
    CONSTRAINT pk_itemtrades PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS jobapplications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    userid bigint NOT NULL,
    buildingid bigint NOT NULL,
    reviewed boolean NOT NULL,
    accepted boolean NOT NULL,
    CONSTRAINT pk_jobapplications PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS nations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NULL,
    description VARCHAR(512) NULL,
    provinceslotsleft integer NOT NULL,
    groupid bigint NOT NULL,
    basepopulationfromusers double precision NOT NULL,
    governorid bigint NULL,
    flagurl VARCHAR(256) NULL,
    basepropertytax double precision NULL,
    propertytaxpersize double precision NULL,
    staticmodifiers jsonb[] NOT NULL,
    titleforprovince text NULL,
    titleforstate text NULL,
    titleforgovernorofaprovince text NULL,
    titleforgovernorofastate text NULL,
    capitalprovinceid bigint NULL,
    CONSTRAINT pk_nations PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS newsposts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    discussionid bigint NOT NULL,
    title character varying(128) NOT NULL,
    content character varying(10000) NOT NULL,
    authorid bigint NOT NULL,
    groupid bigint NOT NULL,
    imageurl text NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    tags character varying(50) NOT NULL,
    viewcount bigint NOT NULL,
    CONSTRAINT pk_newsposts PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS oauthapps (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    secret text NOT NULL,
    ownerid bigint NOT NULL,
    uses integer NOT NULL,
    name text NOT NULL,
    image_url text NOT NULL,
    CONSTRAINT pk_oauthapps PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS producingbuilding (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    employeeid bigint NULL,
    employeegrouproleid bigint NULL,
    quantity double precision NOT NULL,
    upgrades jsonb[] NULL,
    staticmodifiers jsonb[] NULL,
    discriminator text NOT NULL,
    name text NULL,
    nationid bigint NOT NULL,
    size integer NOT NULL,
    recipeid text NOT NULL,
    luabuildingobjid text NOT NULL,
    description text NULL,
    provinceid bigint NOT NULL,
    ownerid bigint NOT NULL,
    successfullyticked boolean NOT NULL,
    CONSTRAINT pk_producingbuilding PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS provinces (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NULL,
    nationid bigint NOT NULL,
    cityid bigint NULL,
    buildingslots integer NOT NULL,
    population bigint NOT NULL,
    populationmultiplier double precision NOT NULL,
    description text NULL,
    governorid bigint NULL,
    stateid bigint NULL,
    developmentvalue integer NOT NULL,
    basedevelopmentvalue integer NOT NULL,
    lasttickdevelopmentvalue integer NOT NULL,
    migrationattraction integer NOT NULL,
    basepropertytax double precision NULL,
    propertytaxpersize double precision NULL,
    staticmodifiers jsonb[] NOT NULL,
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    stringid text NOT NULL,
    ownerid bigint NOT NULL,
    customoutputitemdefinitionid bigint NULL,
    outputs jsonb NOT NULL,
    inputs jsonb NOT NULL,
    perhour double precision NOT NULL,
    baserecipeid text NULL,
    obsolete boolean NOT NULL,
    entityidsthatcanusethisrecipe bigint[] NOT NULL,
    editslevels jsonb NOT NULL,
    anywithbasetypesfilledin jsonb NOT NULL,
    outputitemname text NOT NULL,
    hasbeenused boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS securities (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    balance numeric NOT NULL,
    shares bigint NOT NULL,
    openshares bigint NOT NULL,
    price numeric(30,8) NOT NULL,
    resource text NULL,
    corporationshareclassid bigint NULL,
    corporationid bigint NULL,
    groupid bigint NULL,
    ticker text NOT NULL,
    description text NULL,
    sellvolumethishour bigint NOT NULL,
    buyvolumethishour bigint NOT NULL,
    sellworthtradedthishour bigint NOT NULL,
    buyworthtradedthishour bigint NOT NULL,
    CONSTRAINT pk_securities PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS securityhistories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    securityid bigint NOT NULL,
    balance bigint NOT NULL,
    shares bigint NOT NULL,
    openshares bigint NOT NULL,
    price numeric NOT NULL,
    sellvolumethishour bigint NOT NULL,
    buyvolumethishour bigint NOT NULL,
    sellworthtradedthishour bigint NOT NULL,
    buyworthtradedthishour bigint NOT NULL,
    time timestamp with time zone NOT NULL,
    historytype integer NOT NULL,
    CONSTRAINT pk_securityhistories PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS senators (
    districtid bigint GENERATED BY DEFAULT AS IDENTITY,
    userid bigint NOT NULL,
    CONSTRAINT pk_senators PRIMARY KEY (districtid)
);


CREATE TABLE IF NOT EXISTS states (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NULL,
    description VARCHAR(512) NULL,
    mapcolor text NOT NULL,
    groupid bigint NOT NULL,
    districtid bigint NOT NULL,
    governorid bigint NULL,
    basepropertytax double precision NULL,
    propertytaxpersize double precision NULL,
    CONSTRAINT pk_states PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    date timestamp with time zone NOT NULL,
    stattype integer NOT NULL,
    targetid bigint NULL,
    targettype integer NOT NULL,
    value bigint NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS svitemownerships (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ownerid bigint NOT NULL,
    definitionid bigint NOT NULL,
    amount numeric(16,2) NOT NULL,
    CONSTRAINT pk_svitemownerships PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS taxpolicies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NULL,
    rate numeric NOT NULL,
    nationid bigint NOT NULL,
    taxtype integer NOT NULL,
    minimum numeric(30,10) NOT NULL,
    maximum numeric(30,10) NOT NULL,
    collected numeric NOT NULL,
    target VARCHAR(32) NULL,
    CONSTRAINT pk_taxpolicies PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amount numeric NOT NULL,
    time timestamp with time zone NOT NULL,
    fromid bigint NOT NULL,
    toid bigint NOT NULL,
    transactiontype integer NOT NULL,
    details VARCHAR(1024) NOT NULL,
    isanexpense boolean NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS ubipolicies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    rate numeric NOT NULL,
    anyone boolean NOT NULL,
    applicablerank integer NULL,
    nationid bigint NOT NULL,
    CONSTRAINT pk_ubipolicies PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS updatetimestuffs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    lastprovinceslotgiven timestamp with time zone NOT NULL,
    CONSTRAINT pk_updatetimestuffs PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    discorduserid BIGINT NOT NULL,
    forumxp integer NOT NULL,
    messagexp real NOT NULL,
    commentlikes integer NOT NULL,
    postlikes integer NOT NULL,
    messages integer NOT NULL,
    pointstotal real NOT NULL,
    activeminutes integer NOT NULL,
    pointsthisminute smallint NOT NULL,
    totalpoints integer NOT NULL,
    totalchars integer NOT NULL,
    lastactiveminute timestamp with time zone NOT NULL,
    joined timestamp with time zone NOT NULL,
    rank integer NOT NULL,
    created timestamp with time zone NOT NULL,
    lastsentmessage timestamp with time zone NOT NULL,
    lastmoved timestamp with time zone NOT NULL,
    oauthtoken text NULL,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(2048) NULL,
    taxablebalance numeric(30,10) NOT NULL,
    incometoday numeric(30,2) NOT NULL,
    apikey VARCHAR(36) NOT NULL,
    imageurl text NULL,
    nationid bigint NULL,
    money numeric(30,3) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS votes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    choiceids Char(38)[] NOT NULL,
    date timestamp with time zone NOT NULL,
    electionid bigint NOT NULL,
    invalid boolean NOT NULL,
    userid bigint NOT NULL,
    CONSTRAINT pk_votes PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS buildingrecords (
    buildingid bigint NOT NULL,
    ownerid bigint NOT NULL,
    time timestamp with time zone NOT NULL,
    recordtype integer NOT NULL,
    buildingupradenumid integer NULL,
    levelschanged integer NULL,
    prevownerid bigint NULL,
    newownerid bigint NULL,
    CONSTRAINT pk_buildingrecords PRIMARY KEY (buildingid, ownerid, time),
    CONSTRAINT fk_buildingrecords_producingbuilding_buildingid FOREIGN KEY (buildingid) REFERENCES producingbuilding (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS securityownerships (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ownerid bigint NOT NULL,
    securityid bigint NOT NULL,
    amount bigint NOT NULL,
    CONSTRAINT pk_securityownerships PRIMARY KEY (id),
    CONSTRAINT fk_securityownerships_securities_securityid FOREIGN KEY (securityid) REFERENCES securities (id) ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS ix_buildingrecords_buildingid ON buildingrecords (buildingid);


CREATE INDEX IF NOT EXISTS ix_buildingrecords_ownerid ON buildingrecords (ownerid);


CREATE INDEX IF NOT EXISTS ix_buildingrecords_time ON buildingrecords (time);


CREATE INDEX IF NOT EXISTS ix_corporationshares_corporationid ON corporationshares (corporationid);


CREATE INDEX IF NOT EXISTS ix_corporationshares_entityid ON corporationshares (entityid);


CREATE INDEX IF NOT EXISTS ix_corporationshares_shareclassid ON corporationshares (shareclassid);


CREATE INDEX IF NOT EXISTS ix_entitybalancerecords_entityid ON entitybalancerecords (entityid);


CREATE INDEX IF NOT EXISTS ix_entitybalancerecords_time ON entitybalancerecords (time);


CREATE INDEX IF NOT EXISTS ix_securityhistories_historytype ON securityhistories (historytype);


CREATE INDEX IF NOT EXISTS ix_securityhistories_id ON securityhistories (id);


CREATE INDEX IF NOT EXISTS ix_securityhistories_time ON securityhistories (time);


CREATE INDEX IF NOT EXISTS ix_securityownerships_ownerid ON securityownerships (ownerid);


CREATE INDEX IF NOT EXISTS ix_securityownerships_securityid ON securityownerships (securityid);


CREATE INDEX IF NOT EXISTS ix_stats_date ON stats (date);


CREATE INDEX IF NOT EXISTS ix_stats_stattype ON stats (stattype);


